sudo: required
services:
  - docker

before_install:
  - docker build -t ofovweewere/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ofovweewere/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ca-central-1-355782294313"
  bucket_path: "docker-react"
  on:
    branch: master
